apiVersion: v1
kind: Secret
metadata:
  name: skishop-secrets
  namespace: dukes-ski-chalet
  labels:
    app: dukes-ski-chalet
type: Opaque
stringData:
  DB_USER: "PLACEHOLDER_DB_USER"
  DB_PASSWORD: "PLACEHOLDER_DB_PASSWORD"
  OPENAI_ENDPOINT: "PLACEHOLDER_OPENAI_ENDPOINT"
  OPENAI_APIKEY: "PLACEHOLDER_OPENAI_APIKEY"
